import React, {useEffect} from 'react';
import {useGlobalContext} from '../providers/GlobalContextProvider';

import Layout from '../components/Layout/Layout';

const Tos = () => {
  const {setPageTitle, setMetaDescription} = useGlobalContext();
  useEffect(() => {
    setPageTitle('Terms Of Service | 0xWF');
    setMetaDescription('0xWF Terms of Service and ownership related information');
    // scroll to top of page when navigated to
    window.scrollTo(0, 0);
  }, []);
  return (
    <Layout>
      <section className='bg-white dark:bg-primary-dark-500 text-black dark:text-white px-8 md:px-64 pt-16'>
        <div id="terms-of-service" className=''>
          <h1 className='uppercase font-bold text-4xl'> Terms & Conditions</h1>
          <p className='mt-4'>
            0xWolfpackFinance is a collection of digital artworks (NFTs) running on the Polygon network.
            This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management
            of their own private Polygon wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the
            0xWolfpackFinance smart contract runs on the Polygon network, there is no ability to undo, reverse, or restore any transactions.
          </p>
          <p className='mt-4'>
            This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting
            sole responsibility for any and all transactions involving 0xWolfpackFinance digital collectibles.
          </p>
        </div>
        <div id="ownership-section" className='py-8'>
          <h1 className='uppercase font-bold text-3xl'> Ownership </h1>
          <p className='pt-4'>i. You Own the NFT. Each 0xWF is an NFT on the Polygon blockchain. When you purchase an NFT, you own the underlying 0xWF, the Art, completely. Ownership of the NFT
          is mediated entirely by the Smart Contract and the Polygon Network: at no point may we seize,
          freeze, or otherwise modify the ownership of any 0xWF.</p>
          <p className='pt-4'>ii. Personal Use. Subject to your continued compliance with these Terms, 0xD4V1NC1 grants you a worldwide, royalty-free license to use, copy, and display
          the purchased Art, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal,
          non-commercial use; or (ii) as part of a third party website or application that permits the inclusion, involvement, or participation of your 0xWF,
            provided that the website/application cryptographically verifies each 0xWF owner’s rights to display the Art for their 0xWF to
            ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the 0xWF leaves the website/application.
          </p>
          <p className='pt-4'>iii. Commercial Use. Subject to your continued compliance with these Terms, 0xD4V1NC1  grants you an unlimited, worldwide license to use, copy, and display
           the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g.
           be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in
           this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of 0xWFs generally, provided
           that the marketplace cryptographically verifies each0xWF owner’s rights to display the Art for their 0xWF to ensure that only the actual owner can
           display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of 0xWFs
           generally, provided that the third party website or application cryptographically verifies each 0xWF owner’s rights to display the Art for their 0xWF
           to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased 0xWF leaves
           the website/application; or (iii) earning revenue from any of the foregoing.
          </p>

        </div>
      </section>
    </Layout>
  );
};
export default Tos;
